trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'malkinfedor/pipelines-python-docker'
  dockerHub: 'docker-registry-susin'
  tag: 'test'

steps:
#- task: Docker@2
#  inputs:
#    command: login
#    containerRegistry: $(dockerHub)

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: ./Dockerfile
    tags: |
      test1
      test2
    
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: |
      test1
      
#- task: Docker@2
#  inputs:
#    command: build
#    Dockerfile: '**/Dockerfile'
#    containerRegistry: $(dockerHub)
#    repository: $(imageName)
#    tags: |
#      $(tag)

#- task: Docker@2
#  inputs: 
#    command: push
#    containerRegistry: $(dockerHub)
#    repository: $(imageName)
#    tags: |
#      $(tag)

#- task: Docker@2
#  displayName: Build and Push
#  inputs:
#    command: buildAndPush
#    repository: $(imageName)
#    containerRegistry: $(dockerHub)
#    tags: |
#      tag1
#      tag2
