trigger:
- master

variables:
  imageName: 'malkinfedor/pipelines-python-docker'
  dockerHub: 'docker-registry-susin'
  tag: 'python'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
   
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        # The 'containerRegistry' input has to be in the build step if we want to have tags for the next push step.
        containerRegistry: |
          $(dockerHub) 
        Dockerfile: ./Dockerfile
        tags: |
          $(Build.BuildId)
          good
          
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: |
          $(dockerHub)
        repository: $(imageName)
        command: push
        tags: |
          $(Build.BuildId)
          good
          
    - script: |
        docker image ls
      displayName: 'get the name of the built image'
      
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: deploy_staging
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: SSH@0
      displayName: 'Run shell commands on remote machine'
      inputs:
        sshEndpoint: 'docker-swarm-node-01'
        commands: |
         imagetag=$(Build.BuildId) && echo $imagetag && docker service update pipelines-python --image malkinfedor/pipelines-python-docker:$imagetag
         echo $dockerHubTest
         echo $(dockerHubTest)
         echo $dockerHub
         echo $(dockerHub)
         #docker service update pipelines-python --image malkinfedor/pipelines-python-docker:$(Build.BuildId)
        failOnStdErr: false
      continueOnError: true
      env:
        imagetag: $(Build.BuildId)
        dockerHubTest: '123'
