trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-python-docker'
  dockerHub: 'docker-registry-susin'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: malkinfedor/$(imageName)
    command: build
    Dockerfile: ./Dockerfile
    #tags: |
    #  test1
    #  test2
    
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: malkinfedor/$(imageName)
    command: push
    #tags: |
    #  $(Build.BuildId)
    #  test1
    #  test2
