trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-python-docker'

steps:
- task: Docker@1
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: ./Dockerfile
    
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(docker-registry-susin)
    repository: $(imageName)
    command: push
    tags: |
      test1
      test2
